#!/bin/bash
#
# This script builds the Android release package.

set -e

pushd android
./gradlew assembleRelease
cp khaoswalletcore/build/outputs/aar/khaoswalletcore-release.aar ../build/khaoswalletcore.aar
popd

echo "Now upload build/khaoswalletcore.aar to https://github.com/Khaos-Labs/khaos-wallet-core/releases/tag/$(git describe --long --tags | cut -f 1 -d "-")"
