#!/bin/bash
#
# This script runs the iOS tests.

set -e

pushd swift
xcodegen
pod install
fastlane scan --workspace KhaosWalletCore.xcworkspace --scheme KhaosWalletCore --sdk iphonesimulator --device='iPhone 11' --clean
popd
